import './globals.css'
import '@worldcoin/mini-apps-ui-kit-react/styles.css';
import type { ReactNode } from 'react'
import { MiniKitProvider } from '@/components/MiniKitProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-blue-900 text-white min-h-screen">
        <MiniKitProvider>{children}</MiniKitProvider>
      </body>
    </html>
  );
}

